### ISSUE TITLE
Unmarshal not declared

### ISSUE THREAD

**Issue by Faizan-Pasha** [surrealdb/surrealdb.go#49]
I am using `github.com/surrealdb/surrealdb.go v0.1.1` when I use the command `surrealdb.unmarshal` i get this error 
`unmarshal not declared by package surrealdb`

**Comment by ElecTwix** [comment]
Hey, I addressed this issue in discord before.
It is because there aren't any releases after v0.1.1 but many commits were pushed to the repo.
They were testing for errors and we're going to push another release, but I think they forgot.

You can pull with commit hash.
```bash
go get github.com/surrealdb/surrealdb.go@e0397e6
```


@phughk by any chance could you push the release on Monday?

**Comment by phughk** [comment]
Hey thanks @Faizan-Pasha, @ElecTwix , and @milkyskies ! Yes, will try and get a release out in that case.
